### ISSUE TITLE
Make sure that the document is scrolled to anchor

### ISSUE THREAD

**Issue by darobin** [speced/respec#10]
When processing finishes, find the element and scroll to it.

**Comment by simevidas** [comment]
I’m experiencing an issue on this page: https://rawgit.com/w3c/aria/master/aria/aria.html#aria-placeholder. The page jump a few times and lands on an incorrect position (~200px to low). Could you check if ReSpec is the culprit?

**Comment by darobin** [comment]
It's probably not ReSpec, but it would require more time to be certain.

ReSpec's location-hash fix runs at the very end of the pipeline, it normally works. But this document does a lot of other things. It includes external data, which IIRC is asynchronous and could thus interfere (in which case the fix is to wait for end-all before scrolling). But given the size of the includes I don't think that's the problem, if it were it would be off by a **lot** more.

My theory is that it's some other processing that's specific to that document. It has quite a lot of code that runs off end-all. If that in any way increases the vertical size above the anchor then it would throw it off. We can't really account for specific processing (that happens deliberately after ReSpec is done). If that is the problem, which is most likely, I would suggest that the spec-specific code try to run location-hash again once it's done, or something of that kind.

**Comment by simevidas** [comment]
Hm, I’m looking at https://www.w3.org/Tools/respec/respec-w3c-common in Chrome DevTools. It’s uglified but if I could get my hands on a source map (Chrome enables injecting source map URLs dynamically), I might be able to debug it.

Is there a source file for this library? Maybe I can use it to generate a source map.

**Comment by halindrome** [comment]
No need - Robin is right that it is aria's fault.  I will effect repairs.

On Fri, Apr 10, 2015 at 11:08 AM, Šime Vidas <notifications@github.com>
wrote:

> Hm, I’m looking at https://www.w3.org/Tools/respec/respec-w3c-common in
> Chrome DevTools. It’s uglified but if I could get my hands on a source map
> (Chrome enables injecting source map URLs dynamically), I might be able to
> debug it.
>
> Is there a source file for this library? Maybe I can use it to generate a
> source map.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/10#issuecomment-91603496>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Actually, I lied.  There is no end-all processing in aria.html that effects
the document.  In fact, unless you use a special query string there is no
end-all processing at all.  So.... I am not quite sure what the problem
is.  I will dig into it.

On Fri, Apr 10, 2015 at 12:09 PM, Shane McCarron <halindrome@gmail.com>
wrote:

> No need - Robin is right that it is aria's fault.  I will effect repairs.
>
> On Fri, Apr 10, 2015 at 11:08 AM, Šime Vidas <notifications@github.com>
> wrote:
>
>> Hm, I’m looking at https://www.w3.org/Tools/respec/respec-w3c-common in
>> Chrome DevTools. It’s uglified but if I could get my hands on a source map
>> (Chrome enables injecting source map URLs dynamically), I might be able to
>> debug it.
>>
>> Is there a source file for this library? Maybe I can use it to generate a
>> source map.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/w3c/respec/issues/10#issuecomment-91603496>.
>>
>
>
>
> --
> Shane McCarron
> halindrome@gmail.com
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by darobin** [comment]
@simevidas This is the repo where the source is. It ought to be possible to set `generateSourceMaps` to true to get one out of the (somewhat older, RequireJS-based) build process.
