### ISSUE TITLE
(core/pluralize): Add support for singularize

### ISSUE THREAD

**Issue by sidvishnoi** [speced/respec#1743]
It would be nice if pluralization also works for singularizing terms. For example,
Instead of `<dfn data-lt="bar">bars</dfn>`, we could write `<dfn>bars</dfn>` but still refer to it as `<a>bar</a>` or `<a>bars</a>`.

Presently it works opposite way only. i.e.
`<dfn>bar</dfn>` can be refereed as `<a>bar</a>` or `<a>bars</a>`, but `<dfn>bars</dfn>` cannot be referred as `<a>bar</a>`.

**Comment by devanshbatra04** [comment]
Hi, I want to pick this issue up, since it's tagged as a good first bug. Would love to start contributing.

**Comment by sidvishnoi** [comment]
Hi @devanshbatra04 👋 
Yes. This still is something we would love to have.
Make sure you've gone through our [Developers guide](https://github.com/w3c/respec/wiki/Developers-Guide). Feel free to ask if you have any questions.

**Comment by devanshbatra04** [comment]
@sidvishnoi should we be creating a completely new package (core/singularize?) that gets activated on including singularize in respec config? Or should I update the functionalities in core/pluralize itself?

**Comment by sidvishnoi** [comment]
Update the functionalities in `core/pluralize` itself.
The [pluralize npm package](https://www.npmjs.com/package/pluralize) provides singularize capabilities, so we have to integrate it.

**Comment by devanshbatra04** [comment]
gotcha. thanks :+1:
