### ISSUE TITLE
Respec profiles under w3c.github.io/builds won't be updated

### ISSUE THREAD

**Issue by acka47** [speced/respec#4729]
## Description of problem

Reported in https://github.com/dini-ag-kim/amb/issues/270 for the [DINI profile](https://github.com/speced/respec/blob/main/profiles/dini.js). Apparently, this repo was transferred to another GitHub organization. This breaks the references in specs that are built based on a ReSpec profile, see e.g. https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/ (which I will fix soon, though).

**What happened (e.g., it crashed)?:**

Apparently, this repo was transferred to another GitHub organization. This breaks the references in specs that are built based on a ReSpec profile, see e.g. https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/ (which I will fix soon, though).

**Expected behavior (e.g., it shouldn't crash):**

I would have expected some ind of heads up for ReSpec users before this move. However, as we are already at this point, I am opening this issue for people with a similar problem. 

Maybe it might make sense to keep an archived version of the repo with the builds under the `w3c` organisation and to advise people on how to switch to the new URLs.

**Comment by sidvishnoi** [comment]
Hi, sorry for the lack of heads up. We migrated repo to speced org from W3C recently (https://github.com/speced/respec/issues/4713). I wasn't sure who all were actively using the w3c.github.io version, so decided this breaking approach will be more efficient. 

The resolution: We don't plan to keep providing builds on w3c.github.io/respec (or under new home speced.github.io/respec - even though right now it's available here).

Please use respec from npm (package name: respec). If you want latest version without managing dependencies yourself (at repo or org level), consider using a CDN over npm such us [unpkg](https://unpkg.com/respec/builds/respec-dini.js) or [jsdelivr](https://cdn.jsdelivr.net/npm/respec/builds/respec-dini.js).

I'll pin this issue so it's more visible.

**Comment by sidvishnoi** [comment]
Forked, now w3c.github.io/respec/builds links will continue to work. But they won't be updated due to additional maintenance efforts.

**Comment by acka47** [comment]
> Now w3c.github.io/respec/builds links will continue to work. But they won't be updated due to additional maintenance efforts.

Thanks, that sounds like a reasonable approach. When will you stop the builds under this `speced`´org? I created an issue so that we take care of it ourselves and would be happy to know about the time frame.

**Comment by sidvishnoi** [comment]
We don't have a timeline, but I filed an issue you can watch https://github.com/speced/respec/issues/4730. It'll be some time after that's closed that builds stop getting hosted.
