### ISSUE TITLE
revisionTypes is not documented

### ISSUE THREAD

**Issue by himorin** [speced/respec#4732]
## Description of problem

[revisionTypes](https://github.com/speced/respec/blob/2d6b9ffd277634c27591b5f7de7628740dce05c7/src/w3c/templates/sotd.js#L271C26-L271C40) had introduced to wording changes and several special example markups, but not [documented](https://respec.org/docs/).

**Comment by marcoscaceres** [comment]
No need to document it. The revisions types will be picked up automatically. I've sent PR #4737 to remove `revisionTypes` in a non-breaking way. 

We should find any spec using them and removed that. In ReSpec, we generally try to avoid using configuration options to add content to the document where it's possible to deduce what to add from the content itself.

**Comment by marcoscaceres** [comment]
No need to document it. The revisions types will be picked up automatically. I've sent PR #4737 to remove `revisionTypes` in a non-breaking way. 

We should find any spec using them and removed that. In ReSpec, we generally try to avoid using configuration options to add content to the document where it's possible to deduce what to add from the content itself.

**Comment by himorin** [comment]
Adding automatically via picking up content marking is great, and agree to close this without documenting.
