### ISSUE TITLE
Double period in references

### ISSUE THREAD

**Issue by mattgarrish** [speced/respec#4752]
## Description of problem

**What happened (e.g., it crashed)?:**

Very minor nit, but I noticed that generated references don't account for the last editor already having a period at the end of their name.

For example, you get two periods because of "Jr." in this reference:

> [CSS Cascading and Inheritance Level 5](https://www.w3.org/TR/css-cascade-5/). Elika Etemad; Miriam Suzanne; Tab Atkins Jr.. W3C. 13 January 2022. W3C Candidate Recommendation. URL: https://www.w3.org/TR/css-cascade-5/

**Expected behavior (e.g., it shouldn't crash):**

If the last editor's name ends in a period, omit a second period.

**Comment by marcoscaceres** [comment]
Offending line is here:
https://github.com/speced/respec/blob/0409aa09b262cd828191324cdaace143fb39e420/src/core/render-biblio.js#L235
