### ISSUE TITLE
Question : table CSS broken ?

### ISSUE THREAD

**Issue by tfrancart** [speced/respec#4759]
## Description of problem

**URL to affected spec or repo:**

http://linked-statistics.github.io/xkos/xkos-best-practices.html#namespaces

**What happened (e.g., it crashed)?:**

The namespace table is not properly styled anymore; it used to be different. Similarly, other tables are missing line separators, such as the one in this section : http://linked-statistics.github.io/xkos/xkos-best-practices.html#bp-classification

Screenshot from the snapshot of [how it used to look like from the Internet Archive 07-08-2023](https://web.archive.org/web/20230807010541/http://linked-statistics.github.io/xkos/xkos-best-practices.html#bp-classification):

![image](https://github.com/user-attachments/assets/fc141724-6205-4586-8589-5467bfe5e47f)

**Expected behavior (e.g., it shouldn't crash):**

Tables should be styled, e.g. with a solid line between each row, etc.

Here is the structure of the namespace table:

```html
<section id="namespaces">
    	<h2>Namespaces</h2>
		<p>The vocabularies used in this document are listed in the table below, with their namespaces and associated prefixes.</p>

		<table class="simple">
			<caption>Prefixes used in this document</caption>
			<thead>
				<tr>
					<th>Prefix</th>
					<th>URI</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><b>xkos</b></td>
					<td><b>http://rdf-vocabulary.ddialliance.org/xkos#</b></td>
					<td>SKOS extension for representing statistical classifications ([[XKOS]])</td>
				</tr>
```

And the second mentionned table:

```html
<table class="simple stickyTableHead">
				<caption>Mandatory, Recommended and Optional properties to describe statistical classifications</caption>
				<thead>
					<tr>
						<th>Property
						<th>Lang.</th>
						<th>Card.</th>
						<th>Range</th>
						<th>Description</th>
					</tr>
				</thead>
				<tbody>
					<tr><td colspan="5" class="table-section">Mandatory properties</td></tr>
					<tr>
						<td>`skos:notation`</td>
						<td></td>
						<td>1..1</td>
						<td>`xsd:string`</td>
						<td>The value must be the short name of the classification, with no language tag.</td>
					</tr>
					<tr>
```

ReSpec is imported with

```html
<script src='[https://www.w3.org/Tools/respec/respec-w3c](view-source:https://www.w3.org/Tools/respec/respec-w3c)' class='remove'></script>
```

Thanks !

**Comment by sidvishnoi** [comment]
It was intentional as per https://github.com/speced/respec/pull/4676

**Comment by tfrancart** [comment]
Indeed this was a breaking change for us. Could you please describe how to fix this ? Should we import a new CSS ? Thanks !

**Comment by sidvishnoi** [comment]
Closing as answered in https://github.com/speced/respec/pull/4676#issuecomment-2236012776. Feel free to re-open if needed.
