### ISSUE TITLE
Add Apache 2.0 to list of respec-config licenses

### ISSUE THREAD

**Issue by arnoweiss** [speced/respec#4760]
**Is your feature request related to a problem? Please describe.**
I want to use respec for a non-w3c specification project. The license is determined to be Apache-2.0.

**Describe the solution you'd like**
In the configuration options, the `license` key is an enum.
https://github.com/speced/respec/blob/0409aa09b262cd828191324cdaace143fb39e420/src/w3c/headers.js#L210
I'd like to see Apache 2.0 added to that list.

**Additional context**
As I understand, respec is driven by but not limited to w3c projects. W3c does not permit Apache-2.0 for specification projects. This can be enforced in the build logic as it currently is for CC0 or CC-BY.

https://github.com/speced/respec/blob/0409aa09b262cd828191324cdaace143fb39e420/src/w3c/headers.js#L313

**Describe any alternatives you've considered**
Optionally providing license info via free text would satisfy my use-case but might invite circumvention of enforcement rules (as above).

**Can you or your organization fund the work or help with development?**
I'd be willing to contribute. Getting feedback if the feature is welcome would be great before starting with implementation.

**Comment by marcoscaceres** [comment]
In the past, we've talked about having a "generic" profile to allow what you are requesting above. Basically, it would be a stripped down version of headers.js living in a "generic" (or similarly named) folder - with all the W3C stuff stripped out.

**Comment by marcoscaceres** [comment]
Just to be clear, we can't add it to the W3C profile for the reason you mentioned. Doing it with logic would definitely work, but it would start making things really messy (or messier than headers.js already is... which is pretty messy already).

**Comment by arnoweiss** [comment]
Thanks for the answer - what would it take for me to create a separate profile? I think my requirements are not too specific to fit a "generic" profile.

**Comment by arnoweiss** [comment]
Closing and reopening with different scope
