### ISSUE TITLE
Add generic profile to respec

### ISSUE THREAD

**Issue by arnoweiss** [speced/respec#4770]
**Is your feature request related to a problem? Please describe.**
I want to use respec for a non-w3c specification project. All current profiles include business-logic implemented to satisfy the requirements of specific standardization organizations. This makes it hard to onboard with a new project.

**Describe the solution you'd like**
A generic profile without any reference to a particular organizations internal structure, licensing restrictions and design.

**Additional context**
Follow-up to #4760 

**Describe any alternatives you've considered**
Add Apache 2.0 license to w3c profile 

**Can you or your organization fund the work or help with development?**
We can contribute but require reviews and a preemptive statement if such a contribution is generally welcome.

**Comment by arnoweiss** [comment]
@sidvishnoi - do you have an opinion on this?

**Comment by sidvishnoi** [comment]
Thinking out loud: We'd need to move some things around from `src/core/` and instead add some more generic helpers in core that can be used in other profiles. It's a long term project/goal, but till then, I think the `base` profile should be good enough? 
Maybe we can try creating a `core` profile (https://github.com/speced/respec/issues/3544), but I think it might be best if different projects/organizations create their own profiles as per their need, using core modules (we can publish `src/core` under `respec/core` or separate npm package to simplify that?) than us having a core profile that might not work well for everyone.

**Comment by arnoweiss** [comment]
By `base` profile you mean the one pulled in from `https://www.w3.org/Tools/respec/respec-w3c.js`? If no, can you provide a short example how to use it?

**Comment by sidvishnoi** [comment]
@arnoweiss Example: https://wicg.github.io/web-app-launch/?specStatus=base&group=null

```html
<script src="https://www.w3.org/Tools/respec/respec-w3c.js" defer></script>
<script>
var respecConfig = {
  specStatus: "base"
}
</script>
```

There's still plenty of W3C specific there, so maybe separate core profile (respec-core.js) would be better.

**Comment by arnoweiss** [comment]
Thanks for the hints - I haven't contributed here yet which is why I'm hesitant to trigger a refactoring of the existing codebase. We'll consider building our own profile when it becomes necessary.
