### ISSUE TITLE
Echidna build failure from attempt to display ReSpec error

### ISSUE THREAD

**Issue by gkellogg** [speced/respec#4825]
## Description of problem

**URL to affected spec or repo:**

https://github.com/w3c/rdf-semantics

**What happened (e.g., it crashed)?:**

Automatic Echidna build fails trying to display an error.

**Expected behavior (e.g., it shouldn't crash):**

It should present whatever error triggered the failure.

**Optional, steps to reproduce:**

1.  Download the `better-html` branch from https://github.com/w3c/rdf-semantics.
2. python -m http.server
3. respec -s "http://localhost:8000/spec/" -o /dev/null --verbose -t 20 -e

```
[INFO] [Timeout: 20000ms] Processing resource: http://localhost:8000/rdf-semantics/spec/ ...
[INFO] [Timeout: 20000ms] Launching browser
[INFO] [Timeout: 19572ms] Navigating to http://localhost:8000/rdf-semantics/spec/
[INFO] [Timeout: 19197ms] Navigation complete.
[INFO] [Timeout: 19173ms] Using ReSpec v35.1.2
[INFO] [Timeout: 19173ms] Processing ReSpec document...
file:///opt/homebrew/lib/node_modules/respec/tools/respec2html.js:62
    const message = colors.red(this._formatMarkdown(rsError.message));
                                                            ^

TypeError: Cannot read properties of null (reading 'message')
    at Logger.error (file:///opt/homebrew/lib/node_modules/respec/tools/respec2html.js:62:61)
    at onError (file:///opt/homebrew/lib/node_modules/respec/tools/respecDocWriter.js:55:13)
    at file:///opt/homebrew/lib/node_modules/respec/tools/respecDocWriter.js:337:16

Node.js v22.8.0
```

I'm not sure how `rsError` could be null here, but it relates to generating the term index. If you remove the `<section id="index"></section>` it builds without a problem.

**Comment by gkellogg** [comment]
Ping, can this issue get some attention?

**Comment by sidvishnoi** [comment]
There is something in rdf-semantics repo, which breaks dfn-index. The dfn with id "dfn-rdf-vocabulary" doesn't exist. 

![Image](https://github.com/user-attachments/assets/f7bd306b-6f50-4139-9f2e-a015e0a4d274)


I'm investigating why that dfn doesn't exist, why it was processed if it doesn't exist, and why `rsError` is null in that case.

**Comment by sidvishnoi** [comment]
Something due to:
https://github.com/w3c/rdf-semantics/blob/84888afb49d9d669d1d248005076d3c183709d27/spec/index.html#L1120
and https://github.com/w3c/rdf-semantics/blob/84888afb49d9d669d1d248005076d3c183709d27/spec/index.html#L1120

**Comment by sidvishnoi** [comment]
Figured out. Sent PR.
